// weatherIcons provided by Bas Milius: https://github.com/basmilius/weather-icons
// ClothingIcons and app-logo generated by google gemini

import {useState } from 'react'
import './App.css'
import shirtIcon from './shirt.png'
import jacketIcon from './jacket.png'
import winterJacketIcon from './winterJacket.png'
import sunIcon from './sun.svg'
import cloudsIcon from './clouds.svg'
import sweaterIcon from './sweater.png'
import rainIcon from './rain.svg'
import appLogo from './Logo.jpeg'
import windIcon from './wind.svg'


function App() {
  const [cityName, setCityName] = useState("")
  const [weatherData, setWeatherData] = useState(null)
  const [isHovering, setIsHovering] = useState(false)

  const handleCityNameInput = (e) => {
    setCityName(e.target.value)
  }

const getClothingIcon = (temp) => {
  if (temp < 7) return winterJacketIcon;  
  if (temp < 12) return jacketIcon;       
  if (temp < 15) return sweaterIcon;     
  return shirtIcon;
};

  const weatherIcons = {
    Clear: sunIcon,
    Clouds: cloudsIcon,
    Rain: rainIcon

  }

  const fetchOpenWeatherApi = () => {
    const apiKey = "9af04edca48732aeccdff09b5b7406a3";
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${cityName}&appid=${apiKey}&units=metric`;

    fetch(url)
      .then(response => response.json())
      .then(responseResult => setWeatherData(responseResult))
      .catch(err => console.error("API Fehler:", err))
  }

  return (
    <div>
      <img className='app-logo' src={appLogo}></img>
      <input
        type='text'
        placeholder='Stadtname'
        onChange={handleCityNameInput}
      />
      <button onClick={fetchOpenWeatherApi}>Suchen</button>

      <div className='weather-container'>
        {weatherData?.main && (
          <>
          <div className='tile'><img onClick={() => {weatherData.weather[0].main === "Clear" && alert("Pack deine Sonnebrille ein!")}}
          src={weatherIcons[weatherData.weather[0].main]}></img></div>


            <div className='tile'>
              <img 
                src={getClothingIcon(weatherData.main.temp)}
                className='weather-icon'
                alt={weatherData.weather[0].main}
              />
            </div>
            <div className='tile'>
              <img
              src= {windIcon}
              
              />
              {(weatherData.wind.speed * 3.6).toFixed(1)} km/h
            </div>
            <div
              className="tile"
              onMouseEnter={() => setIsHovering(true)}
              onMouseLeave={() => setIsHovering(false)}
            >
              <span style={{ fontWeight: 'bold' }}>
                {isHovering ? "Gefühlt" : "Temperatur"}
              </span>
              <p>
                {isHovering
                  ? `${Math.round(weatherData.main.feels_like)}°C`
                  : `${Math.round(weatherData.main.temp)}°C`
                }
              </p>
            </div>
            
          </>
        )}
      </div>
      <p>&copy; {new Date().getFullYear()} QuickWeather</p>
    </div>
  )
}

export default App