// weatherIcons provided by Bas Milius: https://github.com/basmilius/weather-icons
// ClothingIcons and app-logo generated by google gemini

import shirtIcon from './shirt.png'
import jacketIcon from './jacket.png'
import winterJacketIcon from './winterJacket.png'
import sunIcon from './sun.svg'
import cloudsIcon from './clouds.svg'
import sweaterIcon from './sweater.png'
import rainIcon from './rain.svg'
import appLogo from './Logo.jpeg'
import windIcon from './wind.svg'

export const icons = {
  shirt: shirtIcon,
  jacket: jacketIcon,
  winterJacket: winterJacketIcon,
  sun: sunIcon,
  clouds: cloudsIcon,
  sweater: sweaterIcon,
  rain: rainIcon,
  logo: appLogo,
  wind: windIcon
};

export const getClothingIcon = (temp) => {
  if (temp < 7) return icons.winterJacket;
  if (temp < 12) return icons.jacket;
  if (temp < 15) return icons.sweater;
  return icons.shirt;
};