// weatherIcons provided by Bas Milius: https://github.com/basmilius/weather-icons
// ClothingIcons and app-logo generated by google gemini

import shirtIcon from '/assets/icons/shirt.png'
import jacketIcon from '/assets/icons/jacket.png'
import winterJacketIcon from '/assets/icons/winterJacket.png'
import sunIcon from '/assets/icons/sun.svg'
import cloudsIcon from '/assets/icons/clouds.svg'
import sweaterIcon from '/assets/icons/sweater.png'
import rainIcon from '/assets/icons/rain.svg'
import appLogo from '/assets/icons/Logo.png'
import windIcon from '/assets/icons/wind.svg'

export const icons = {
  shirt: shirtIcon,
  jacket: jacketIcon,
  winterJacket: winterJacketIcon,
  sun: sunIcon,
  clouds: cloudsIcon,
  sweater: sweaterIcon,
  rain: rainIcon,
  logo: appLogo,
  wind: windIcon,
};

export const getClothingIcon = (temp) => {
  if (temp < 7) return icons.winterJacket;
  if (temp < 12) return icons.jacket;
  if (temp < 15) return icons.sweater;
  return icons.shirt;
};